### ISSUE TITLE
check_story_point_in_the_title v4

### ISSUE THREAD

**Issue by akiraisomura** [akiraisomura/github_utils#8]
## TODO
- [ ] paging
- [ ] use v4 api for posting
- [ ] use module for v4, v3
- [ ] docker
- [ ] To enable support for multiple repositories within the project
